export interface Merchantdetails {
    id: number,
    merchant_id: number, 
    sub_merchant_id: number,
    sub_merchant_location_id: number,
    username: string,
    email: string,
    first_name: string,
    last_name: string,
    password: string,
    gender: number,
    contact: string,
    //avatar: string,
    //status: number,
    //skip_ip_check: number,
    user_type_id: number,
    //remember_token: string,
    created_by: number,
    // updated_by: number,
    // created_at: any,
    // updated_at: any,
    // deleted_at: any,
}