export interface CustomerOrder {
    StoreCode: string,
    ShrmDesc: string,
    CreateDate: string,
    Time: string,
    CustomerNumber: string,
    MobileNo: string,
    InvoiceNumber: string,
    GrossAmt: string,
    NetAmount: string,
    Cash: string,
    Card: string,
    Cheque: string,
    GV: string,
    CreditNote: string,
    ExcessGV: string,
    RoundOff: string,
    NoRefound: string,
    OtherPayments: string,
    LegacyGiftVoucher: string,
    LegacyAdvOrder: string,
    AgentAccount: string,
    MallGiftVoucher: string,
    LineDisc: string,
    HeaderDisc: string
}